server:
  port: 8080

spring:
  application:
    name: UpNest Edu System

  datasource:
    # URL kết nối: localhost cổng 1433, tên DB là UpNestEdu
    # encrypt=true;trustServerCertificate=true là bắt buộc để chạy local không lỗi SSL
    url: jdbc:sqlserver://localhost:1433;databaseName=UpNestEdu;encrypt=true;trustServerCertificate=true;
    username: thuynhung                # Tên đăng nhập SQL Server (thường là sa)
    password: 1234abc   # <--- QUAN TRỌNG: SỬA THÀNH MẬT KHẨU SQL CỦA BẠN
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true              # Hiện câu lệnh SQL ra màn hình
    hibernate:
      ddl-auto: update          # Tự động tạo bảng nếu chưa có
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect

# Cấu hình Token bảo mật (JWT)
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000       # 1 ngày
      refresh-token:
        expiration: 604800000    # 7 ngày